version: "3"
services:
  ros:
    build:
      context: .
      args:
        - UID=${UID}
        - GID=${GID}
        - USERNAME=${USERNAME}
        - GROUPNAME=${GROUPNAME}
        - PASSWORD=${PASSWORD}
    network_mode: "host"
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
    working_dir: /workspace
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
