# ベースイメージの指定
FROM ros:humble
SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Tokyo
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

RUN apt-get update && apt-get install -y --no-install-recommends \
    locales \
    sudo \
    x11-apps \
    curl \
    vim \
    sudo\
    python3-pip \
    python3-colcon-argcomplete \
    python3-colcon-common-extensions \
    ros-humble-ros-base \
    ros-humble-ros2bag \
    ros-humble-rosbag2-storage-default-plugins \
    ros-humble-rqt-py-common \
    && rm -rf /var/lib/apt/lists/* 


ARG UID GID LOCAL_USERNAME LOCAL_GROUPNAME
RUN groupadd -g $GID $LOCAL_GROUPNAME && \
    useradd -m -u $UID -g $GID $LOCAL_USERNAME && \
    usermod -aG sudo $LOCAL_USERNAME && \
    echo "$LOCAL_USERNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers &&\
    chmod 0440 /etc/sudoers


RUN python3 -m pip install --upgrade pip setuptools && \
    python3 -m pip install \
    jupyterlab \
    ipykernel \
    pandas \
    matplotlib \
    black \
    jupyterlab-lsp \
    'python-lsp-server[all]' \
    lckr-jupyterlab-variableinspector \
    jupyterlab_code_formatter \
    jupyterlab-git \
    jupyterlab_widgets \
    ipywidgets \
    import-ipynb


RUN python3 -m ipykernel install --user --name=ros-humble-kernel --display-name "ROS 2 Humble Python"
RUN curl -fsSL https://starship.rs/install.sh | sh -s -- --yes 


# ワークスペース
ARG LOCAL_USERNAME
ARG WS=/home/$LOCAL_USERNAME/dev_ws
RUN mkdir -p $WS/src
WORKDIR $WS
USER $LOCAL_USERNAME:$LOCAL_GROUPNAME

# stop alert bell
RUN touch ~/.inputrc && \
    echo "# quit beep sound" >> ~/.inputrc && \
    echo "set bell-style none" >> ~/.inputrc

RUN mkdir -p /home/$LOCAL_USERNAME/dev_ws/src \
    && source /opt/ros/humble/setup.bash \
    && sudo apt-get update \
    && if [ ! -f /etc/ros/rosdep/sources.list.d/20-default.list ]; then sudo rosdep init; fi \
    && rosdep update \
    && rosdep install --from-paths /home/$LOCAL_USERNAME/dev_ws/src --rosdistro humble -i -y \
    && echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc 

COPY requirements.txt /home/$LOCAL_USERNAME
RUN pip install --upgrade pip && \
    pip install --upgrade 'setuptools==58.0.0' && \
    pip3 install --no-cache-dir -r /home/$LOCAL_USERNAME/requirements.txt

RUN sudo apt-get update && sudo apt-get install -y \
    openssh-client 

RUN mkdir -p ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
RUN echo "eval $(starship init bash)" >> ~/.bashrc
